title = "元素碎语"
theme = "PaperMod"
baseURL = "https://www.fe3o4.top"

languageCode = "zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "元素碎语"
  description = "Fe3O4 的小站"
  keywords = ["博客", "Blog", "个人", "Personal", "元素", "Element", "四氧化三铁", "Fe3O4", "计算机", "技术", "IT", "生活", "随笔", "Life", "Hugo", "PaperMod"]
  author = "Fe3O4"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  showtoc = true
  # tocopen = true
  comments = true

[params.editPost]
  URL = "https://github.com/Fe3O4-Git/Fe3O4-Git.github.io.source/tree/master/content"
  Text = "提供修改建议"
  appendFilePath = true

[params.homeInfoParams]
  Title = "欢迎"
  Content = "这里是一只什么都不会的四氧化三铁的小站"

[[params.socialIcons]]
  name = "qq"
  url = "https://wpa.qq.com/msgrd?v=3&uin=1935969597&site=qq&menu=yes"

[[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/ItsNaClO"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/Fe3O4_1"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Fe3O4-Git"

[[params.socialIcons]]
  name = "email"
  url = "mailto:Fe3O4_Live@Outlook.com"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags"
  weight = 2

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives"
  weight = 3

[[menu.main]]
  identifier = "friends"
  name = "友链"
  url ="/friends"
  weight = 4

[[menu.main]]
  identifier = "about"
  name = "关于"
  url ="/about"
  weight = 5

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search"
  weight = 10
