title = "元素碎语"
theme = "PaperMod"
baseURL = "https://www.fe3o4.top"
#languageCode = "zh"
#defaultContentLanguage = "zh"
#defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  ShowReadingTime = true

[params.homeInfoParams]
  Title = "欢迎"
  Content = "这里是一只什么都不会的四氧化三铁的小站"

[[params.socialIcons]]
  name = "qq"
  url = "https://wpa.qq.com/msgrd?v=3&uin=1935969597&site=qq&menu=yes"

[[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/ItsNaClO"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Fe3O4-Git"

[[params.socialIcons]]
  name = "email"
  url = "mailto:Fe3O4_Live@Outlook.com"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[[menu.main]]
  identifier = "about"
  name = "关于"
  url ="/about"
  weight = 1

[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags"
  weight = 3

[[menu.main]]
  identifier = "archives"
  name = "时间线"
  url = "/archives"
  weight = 4

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search"
  weight = 10
