#!/bin/fish

set server_args -D -E -F --enableGitInfo --printI18nWarnings --printMemoryUsage --printPathWarnings --printUnusedTemplates

function init
    git submodule update --init --recursive
end

function update
    git submodule update --remote --merge
end

function new
    read name -p "echo Enter new post name:"
    set path "posts/"$name".md"
    hugo new $path
    kate "content/"$path >/dev/null 2>&1 &
end

function server
    xdg-open http://localhost:1313 >/dev/null 2>&1
    hugo server $server_args
end

function commit
    read msg -p "echo Enter commit message, leave blank to use default:"
    if not test -n "$msg"
        set msg "site update "(date -I)
    end
    git add .
    git commit -m $msg
end

function push
    git push origin master
end

switch $argv[1]
    case init i
        init
    case update u
        update
    case new n
        new
    case server s
        server
    case commit c
        commit
    case push p
        push
    case "*"
        cat ./helper_of_helper
end
